pi:
  ssid: wireless1
  passowrd: testpw!\/

mqtt:
  host: 192.168.20.2
  port: 1883
  user: ""
  password: ""
  topic_prefix: home/wateringsystem/back
  ha_discovery:
    enabled: yes

digital_outputs:
  - name: $name
    pin: 17
    on_payload: "ON"
    off_payload: "OFF"
